/**
* Ze API
* description
*
* OpenAPI spec version: 1.0.0
* Contact: martin.binder@qaware.de
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param greeting 
 */
data class HelloDTO (
    val greeting: kotlin.String,

) {

}
