/* 
 * Ze API
 *
 * description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: martin.binder@qaware.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type HelloDto struct {

	Greeting string `json:"greeting"`
}
