/**
 * Ze API
 * description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: martin.binder@qaware.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/HelloDTO'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/HelloDTO'));
  } else {
    // Browser globals (root is window)
    if (!root.ZeApi) {
      root.ZeApi = {};
    }
    root.ZeApi.GreetApi = factory(root.ZeApi.ApiClient, root.ZeApi.HelloDTO);
  }
}(this, function(ApiClient, HelloDTO) {
  'use strict';

  /**
   * Greet service.
   * @module api/GreetApi
   * @version 1.0.0
   */

  /**
   * Constructs a new GreetApi. 
   * @alias module:api/GreetApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the greetingGet operation.
     * @callback module:api/GreetApi~greetingGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/HelloDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * the first service - greetings!
     * just say hello!
     * @param {module:api/GreetApi~greetingGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/HelloDTO}
     */
    this.greetingGet = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = HelloDTO;

      return this.apiClient.callApi(
        '/greeting', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the greetingWithNameGet operation.
     * @callback module:api/GreetApi~greetingWithNameGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/HelloDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Greeting with name
     * @param {String} greetingName 
     * @param {module:api/GreetApi~greetingWithNameGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/HelloDTO}
     */
    this.greetingWithNameGet = function(greetingName, callback) {
      var postBody = null;

      // verify the required parameter 'greetingName' is set
      if (greetingName === undefined || greetingName === null) {
        throw new Error("Missing the required parameter 'greetingName' when calling greetingWithNameGet");
      }


      var pathParams = {
      };
      var queryParams = {
        'greetingName': greetingName
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = HelloDTO;

      return this.apiClient.callApi(
        '/greetingWithName', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
