/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.HelloDTO;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-01-16T15:59:00.749Z")

@Api(value = "greeting", description = "the greeting API")
public interface GreetingApi {

    @ApiOperation(value = "the first service - greetings!", notes = "just say hello!", response = HelloDTO.class, tags={ "greet", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = HelloDTO.class),
        @ApiResponse(code = 500, message = "some error occured during service execution", response = Integer.class) })
    
    @RequestMapping(value = "/greeting",
        method = RequestMethod.GET)
    ResponseEntity<HelloDTO> greetingGet();

}
